### PR TITLE
Return Conflicting LB

### LINKED ISSUE #270: Conflicting LB Not Returned upon Creation
Creating a new LB with a slug that's already in use doesn't return the board using it.

### Step(s) to Reproduce
Create a LB. Create a second LB using the same slug.

### Expected Result
A problem details containing the first (conflicting) LB is returned.

### Actual Outcome
A validation problem details object is returned.

### Notes
It might be a good idea to use plain record types for result types that contain references to other objects, thereby making their constructors required and providing public immutable members by default.

```cs
public record Conflict<T>(T Conflicting);
```

### PR DESCRIPTION
**Pull request by TheTedder**
Closes #270 and fixes the restore LB endpoint too.

### CODE REVIEW

File: LeaderboardBackend/Results.cs [hunk 1]
```diff
@@ -9,7 +9,7 @@ namespace LeaderboardBackend.Result;
 public readonly record struct BadCredentials;
 public readonly record struct BadRole;
 public readonly record struct ConfirmationNotFound;
-public readonly record struct Conflict<T>(T Conflicting);
+public record Conflict<T>(T Conflicting);
```
Comment (zysim) [inline LeaderboardBackend/Results.cs:12]: Why the change? .net doesn't like it if you keep it a read-only record struct?

Comment (TheTedder) [reply LeaderboardBackend/Results.cs:12]: Doing it this way forces you to actually use the constructor, leading to fewer code errors.

**Review by zysim — APPROVED** [review]
